# Generated by Django 3.1.2 on 2021-05-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_inverstor_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='education',
            field=models.CharField(choices=[('primary school degree', 'Primary School Degree'), ('high school degree', 'High School Degree'), ('college degree', 'College Degree'), ('master degree', 'Master Degree'), ('phd degree', 'PhD Degree')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='occupation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
