# Generated by Django 3.1.2 on 2021-05-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210510_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='occupation',
            field=models.CharField(choices=[('unemployeed', 'Unemployeed'), ('student', 'Student'), ('recent graduate', 'Recent Graduate'), ('business owner', 'Business Owner'), ('private job', 'Private Job'), ('goverment job', 'Goverment Job')], max_length=100, null=True),
        ),
    ]
