# Generated by Django 3.1.2 on 2021-05-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210510_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='inverstor',
            name='types',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='sector',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inverstor',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
