# Generated by Django 3.1.2 on 2021-05-11 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210510_2036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inverstor',
            new_name='Investor',
        ),
    ]
