# Generated by Django 3.1.2 on 2021-05-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210510_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='types',
            field=models.CharField(choices=[('type1', 'Type1'), ('type2', 'Type2')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='sector',
            field=models.CharField(choices=[('private sector', 'Private Sector'), ('public sector', 'Public Sector'), ('third sector', 'Third Sector')], max_length=100, null=True),
        ),
    ]
