# Generated by Django 3.1.2 on 2021-06-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210510_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
