# Generated by Django 3.1.2 on 2021-06-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20210608_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
