# Generated by Django 3.1.2 on 2021-06-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20210609_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='user',
        ),
    ]
